instance-prefix: "main-{id}"

is-under-proxy: false # Set to true if you are running the server under a proxy
allow-transfer-packets: false # If under a proxy, set 'is-under-proxy' to true and set this to true

redis:
  host: "127.0.0.1"
  port: 6379

mysql:
  host: "127.0.0.1"
  port: 3306
  database: ""
  username: ""
  password: ""

player-data: # What is being saved to database to allow for syncing across instances
