name: Build Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "corretto"
      - name: Gradle Build
        run: gradle clean :shadowJar
